/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.starcritic.dam_proyect.view;

import com.starcritic.dam_proyect.model.pojo.itemList.ItemContent;
import com.starcritic.dam_proyect.model.pojo.itemList.ItemContentRender;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author jsb
 */
public class AdminContentDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminContentDialog.class.getName());

    /**
     * Creates new form AdminContentDialog
     */
    public AdminContentDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initList();
        applyStyle();
        pack();
        setLocationRelativeTo(parent);
    }

    public AdminContentDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initList();
        applyStyle();
        pack();
        setLocationRelativeTo(parent);
    }

    private void applyStyle() {
        setTitle("Star Critic — Administrar contenido");
        getContentPane().setBackground(UIStyle.BG_PRIMARY);
        backgroundPanel.setBackground(UIStyle.BG_PRIMARY);
        backgroundPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 24, 20, 24));

        searchLabel.setFont(new java.awt.Font(UIStyle.FONT_FAMILY, java.awt.Font.BOLD, 16));
        searchLabel.setForeground(UIStyle.ACCENT);
        UIStyle.styleField(searchTextField);
        UIStyle.stylePrimaryButton(searchButton);

        filmScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(UIStyle.BORDER, 1, true));
        filmScrollPane.getViewport().setBackground(UIStyle.BG_CARD);
        if (searchList != null) {
            UIStyle.styleList(searchList);
        }

        UIStyle.stylePrimaryButton(addButton);
        UIStyle.styleSecondaryButton(modificarButton);
        UIStyle.styleSecondaryButton(destacarButton);
        UIStyle.styleSecondaryButton(ocultarButton);
        UIStyle.styleDangerButton(deleteButton);
        UIStyle.styleDangerButton(cancelButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        searchLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        modificarButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        filmScrollPane = new javax.swing.JScrollPane();
        destacarButton = new javax.swing.JButton();
        ocultarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchButton.setText("Buscar");

        searchLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchLabel.setText("Buscar:");

        searchTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchTextField.setText("");

        cancelButton.setText("Cancel");

        addButton.setText("Añadir...");

        modificarButton.setText("Modificar...");

        deleteButton.setText("Eliminar...");

        filmScrollPane.setBorder(null);
        filmScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        destacarButton.setText("Destacar");

        ocultarButton.setText("Ocultar");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(searchLabel)
                        .addGap(18, 18, 18)
                        .addComponent(searchTextField)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(destacarButton)
                        .addGap(18, 18, 18)
                        .addComponent(ocultarButton)
                        .addGap(18, 18, 18)
                        .addComponent(modificarButton)
                        .addGap(18, 18, 18)
                        .addComponent(addButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton))
                    .addComponent(filmScrollPane))
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchLabel)
                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchButton)))
                .addGap(18, 18, 18)
                .addComponent(filmScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(addButton)
                    .addComponent(modificarButton)
                    .addComponent(deleteButton)
                    .addComponent(destacarButton)
                    .addComponent(ocultarButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initList() {
        modelSearch = new DefaultListModel<>();
        searchList = new JList<>(modelSearch);
        searchList.setCellRenderer(new ItemContentRender());
        filmScrollPane.setViewportView(searchList);
    }

    public void setCancelButtonListener(ActionListener al) {
        this.cancelButton.addActionListener(al);
    }

    public void setAddButtonListener(ActionListener al) {
        this.addButton.addActionListener(al);
    }

    public void setEditButtonListener(ActionListener al) {
        this.modificarButton.addActionListener(al);
    }

    public void setDeleteButtonListener(ActionListener al) {
        this.deleteButton.addActionListener(al);
    }

    public void setSearchButtonListener(ActionListener al) {
        this.searchButton.addActionListener(al);
    }

    public void setDestacarButtonListener(ActionListener al){
        this.destacarButton.addActionListener(al);
    }

    public void setOcultarButtonListener(ActionListener al){
        this.ocultarButton.addActionListener(al);
    }

    public void setDestacarButtonText(String text) {
        this.destacarButton.setText(text);
    }

    public void setOcultarButtonText(String text) {
        this.ocultarButton.setText(text);
    }

    public void setListSelectionListener(ListSelectionListener listener) {
        this.searchList.addListSelectionListener(listener);
    }

    public String getSearchText() {
        return this.searchTextField.getText();
    }

    public void addElementSearch(ItemContent item) {
        modelSearch.addElement(item);
    }

    public void clearList() {
        modelSearch.clear();
    }

    public int getSelectedIndex() {
        return searchList.getSelectedIndex();
    }

    public ItemContent getSelectedItem() {
        return searchList.getSelectedValue();
    }

    public boolean removeSelectedElement() {
        int idx = searchList.getSelectedIndex();
        if (idx < 0) {
            return false;
        }
        modelSearch.remove(idx);
        return true;
    }


    public boolean removeElementById(String id) {
        for (int i = 0; i < modelSearch.size(); i++) {
            if (modelSearch.get(i).getId().equals(id)) {
                modelSearch.remove(i);
                return true;
            }
        }
        return false;
    }


    private DefaultListModel<ItemContent> modelSearch;
    private JList<ItemContent> searchList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton destacarButton;
    private javax.swing.JButton ocultarButton;
    private javax.swing.JScrollPane filmScrollPane;
    private javax.swing.JButton modificarButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
