/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.starcritic.dam_proyect.view;

import com.starcritic.dam_proyect.util.ImageUtils;
import java.awt.Font;
import java.awt.Image;
import java.awt.MediaTracker;
import java.awt.event.ActionListener;
import java.net.URI;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

/**
 * Diálogo que muestra la ficha completa de un contenido (titulo, póster,
 * sinopsis, géneros, etiquetas) y permite al usuario guardarlo en lista,
 * escribir critica o ver criticas.
 * @author Jesús Santos Baquero
 */
public class CompleteItemDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CompleteItemDialog.class.getName());

    /**
     * Creates new form CompleteItemDialog
     */
    public CompleteItemDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        applyStyle();
        pack();
        setLocationRelativeTo(parent);
    }

    public CompleteItemDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        applyStyle();
        pack();
        setLocationRelativeTo(parent);
    }

    private void applyStyle() {
        getContentPane().setBackground(UIStyle.BG_PRIMARY);
        backgroundPanel.setBackground(UIStyle.BG_PRIMARY);
        backgroundPanel.setBorder(BorderFactory.createEmptyBorder(24, 30, 24, 30));

        titleLabel.setFont(new Font(UIStyle.FONT_FAMILY, Font.BOLD, 26));
        titleLabel.setForeground(UIStyle.TITLE);

        ratingLabel.setFont(new Font(UIStyle.FONT_FAMILY, Font.BOLD, 20));
        ratingLabel.setForeground(UIStyle.ACCENT);

        genreLabel.setFont(new Font(UIStyle.FONT_FAMILY, Font.PLAIN, 13));
        genreLabel.setForeground(UIStyle.TEXT_MUTED);
        tagsLabel.setFont(new Font(UIStyle.FONT_FAMILY, Font.PLAIN, 13));
        tagsLabel.setForeground(UIStyle.ACCENT_DARK);

        descriptionLabel.setFont(new Font(UIStyle.FONT_FAMILY, Font.PLAIN, 13));
        descriptionLabel.setForeground(UIStyle.TEXT);

        posterLabel.setBorder(null);
        posterLabel.setOpaque(false);

        UIStyle.stylePrimaryButton(saveInListButton);
        UIStyle.styleSecondaryButton(criticButton);
        UIStyle.styleDangerButton(cancelButton);
        setTitle("Star Critic — Detalle");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        posterLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        ratingLabel = new javax.swing.JLabel();
        saveInListButton = new javax.swing.JButton();
        criticButton = new javax.swing.JButton();
        genreLabel = new javax.swing.JLabel();
        tagsLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setText("");

        ratingLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ratingLabel.setText("");

        saveInListButton.setText("Guardar en lista...");

        criticButton.setText("Ver críticas...");

        genreLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        genreLabel.setText("");

        tagsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tagsLabel.setText("");

        descriptionLabel.setText("");

        cancelButton.setText("Cancelar");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveInListButton)
                        .addGap(18, 18, 18)
                        .addComponent(criticButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(posterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ratingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 34, Short.MAX_VALUE))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(genreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tagsLabel)
                                .addGap(188, 188, 188))))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(descriptionLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ratingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tagsLabel)))
                    .addComponent(posterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(descriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criticButton)
                    .addComponent(saveInListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelButton))
                .addGap(20, 20, 20))
        );

        posterLabel.getAccessibleContext().setAccessibleName("JLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static final int POSTER_MAX = 200;

    public void setPosterLabel(String posterUrl) {
        if (posterUrl == null || posterUrl.isBlank() || posterUrl.equalsIgnoreCase("N/A")) {
            posterLabel.setIcon(scaledPoster(new ImageIcon(getClass().getResource("/img/defaultPoster.png")).getImage()));
        } else {
            try {
                URI imgURL = new URI(posterUrl);
                Image img = new ImageIcon(imgURL.toURL()).getImage();
                posterLabel.setIcon(scaledPoster(img));
            } catch (Exception ex) {
                posterLabel.setIcon(scaledPoster(new ImageIcon(getClass().getResource("/img/defaultPoster.png")).getImage()));
            }
        }
    }

    private ImageIcon scaledPoster(Image img) {
        MediaTracker tracker = new MediaTracker(this);
        tracker.addImage(img, 0);
        try { tracker.waitForAll(); } catch (InterruptedException ignored) {}
        int origW = img.getWidth(null);
        int origH = img.getHeight(null);
        if (origW <= 0 || origH <= 0) {
            return new ImageIcon(ImageUtils.scale(img, POSTER_MAX, POSTER_MAX));
        }
        double scale = Math.min((double) POSTER_MAX / origW, (double) POSTER_MAX / origH);
        int w = (int) (origW * scale);
        int h = (int) (origH * scale);
        return new ImageIcon(ImageUtils.scale(img, w, h));
    }

    public void setTitleLabel(String value) {
        titleLabel.setText(value);
    }

    public void setRatingLabel(String value) {
        ratingLabel.setText(value);
    }

    public void enableUserOptions(boolean value) {
        saveInListButton.setEnabled(value);
        saveInListButton.setVisible(value);
    }

    public void setSaveInListButton(ActionListener al) {
        this.saveInListButton.addActionListener(al);
    }

    public void setCriticButton(ActionListener al) {
        this.criticButton.addActionListener(al);
    }

    public void setGenreLabelText(String text) {
        this.genreLabel.setText(text);
    }

    public void setDescriptionLabelText(String text) {
        this.descriptionLabel.setText("<html><div style='width:500px;'>" + text + "</div></html>");
    }

    public void setTagsLabelText(String text) {
        this.tagsLabel.setText(text);
    }
    
    public void setCancelButtonListener(ActionListener al){
        this.cancelButton.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton criticButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JLabel posterLabel;
    private javax.swing.JLabel ratingLabel;
    private javax.swing.JButton saveInListButton;
    private javax.swing.JLabel tagsLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
