/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.starcritic.dam_proyect.view;

import com.starcritic.dam_proyect.model.pojo.bd.Aspecto;
import com.starcritic.dam_proyect.model.pojo.bd.Origen;
import com.starcritic.dam_proyect.model.pojo.itemList.ItemCritic;
import com.starcritic.dam_proyect.model.pojo.itemList.ItemCriticRender;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.ListSelectionListener;

/**
 * Diálogo que muestra las criticas de un contenido agrupadas por aspecto.
 * Incluye una lista de aspectos a la izquierda y las criticas del aspecto
 * seleccionado a la derecha.
 * @author Jesús Santos Baquero
 */
public class CriticsDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CriticsDialog.class.getName());
    private static final int ASPECT_SCROLL_WIDTH = 551;
    private static final int ASPECT_SCROLL_HEIGHT = 50;
    private static final int ASPECT_CELL_WIDTH = 130;
    private static final int ASPECT_CELL_HEIGHT = 30;

    public CriticsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initLists();
        applyStyle();
        pack();
        setLocationRelativeTo(parent);
    }

    public CriticsDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initLists();
        applyStyle();
        pack();
        setLocationRelativeTo(parent);
    }

    private void applyStyle() {
        getContentPane().setBackground(UIStyle.BG_PRIMARY);
        backgroundPanel.setBackground(UIStyle.BG_PRIMARY);
        backgroundPanel.setBorder(BorderFactory.createEmptyBorder(20, 24, 20, 24));

        UIStyle.stylePrimaryButton(AddButton);
        AddButton.setFont(new Font(UIStyle.FONT_FAMILY, Font.BOLD, 14));
        UIStyle.styleDangerButton(deleteButton);
        UIStyle.styleDangerButton(cancelButton);

        ratingLabel.setFont(new Font(UIStyle.FONT_FAMILY, Font.BOLD, 18));
        ratingLabel.setForeground(UIStyle.ACCENT);

        aspectScrollPane.setBorder(BorderFactory.createLineBorder(UIStyle.BORDER, 1, true));
        aspectScrollPane.getViewport().setBackground(UIStyle.BG_CARD);
        criticsScrollPane.setBorder(BorderFactory.createLineBorder(UIStyle.BORDER, 1, true));
        criticsScrollPane.getViewport().setBackground(UIStyle.BG_CARD);
        if (aspectList != null) {
            UIStyle.styleList(aspectList);
        }
        if (criticsList != null) {
            UIStyle.styleList(criticsList);
        }
        setTitle("Star Critic — Críticas");
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        AddButton = new javax.swing.JButton();
        aspectScrollPane = new javax.swing.JScrollPane();
        criticsScrollPane = new javax.swing.JScrollPane();
        ratingLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        AddButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddButton.setText("Hacer critica");

        aspectScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        aspectScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        criticsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        ratingLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ratingLabel.setText("");

        cancelButton.setText("Cancelar");

        deleteButton.setText("Eliminar...");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(criticsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addComponent(aspectScrollPane))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ratingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(aspectScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(ratingLabel))
                .addGap(18, 18, 18)
                .addComponent(criticsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(deleteButton))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void initLists() {
        aspectListModel = new DefaultListModel<>();
        criticaListModel = new DefaultListModel<>();
        aspectList = new JList<>(aspectListModel);
        aspectList.setVisibleRowCount(1);
        aspectList.setLayoutOrientation(JList.HORIZONTAL_WRAP);
        aspectList.setFixedCellWidth(ASPECT_CELL_WIDTH);
        aspectList.setFixedCellHeight(ASPECT_CELL_HEIGHT);
        criticsList = new JList<>(criticaListModel);
        criticsList.setCellRenderer(new ItemCriticRender());
        Dimension aspectSize = new Dimension(ASPECT_SCROLL_WIDTH, ASPECT_SCROLL_HEIGHT);
        aspectScrollPane.setPreferredSize(aspectSize);
        aspectScrollPane.setMaximumSize(aspectSize);
        aspectScrollPane.setMinimumSize(aspectSize);
        aspectScrollPane.setViewportView(aspectList);
        criticsScrollPane.setViewportView(criticsList);
    }

    public void clearCriticas() {
        criticaListModel.clear();
        criticsList.revalidate();
        criticsList.repaint();
    }

    public int getSelectedCritic(){
        return this.criticsList.getSelectedIndex();
    }
    
    public int getSelectID(int row){
        return this.criticaListModel.get(row).getIdCritica();
    }
 
    public void aspectListMouseListener(MouseListener ml) {
        aspectList.addMouseListener(ml);
    }
    
    public void setAspectListListener(ListSelectionListener lsl){
        aspectList.addListSelectionListener(lsl);
    }
    
    public void setAddButtonListener(ActionListener al) {
        AddButton.addActionListener(al);
    }
    public void setCancelButtonListener(ActionListener al){
        cancelButton.addActionListener(al);
    }
    public void setDeleteButtonListener(ActionListener al){
        deleteButton.addActionListener(al);
    }
    
    public void enableModifyButton(boolean value) {
        enableAddButton(value);
        deleteButton.setEnabled(value);
        deleteButton.setVisible(value);
        
    }
    public void enableAddButton(boolean value){
        AddButton.setEnabled(value);
        AddButton.setVisible(value);
    }
    public Aspecto getSelectedAspect(){
        return this.aspectList.getModel().getElementAt(this.aspectList.getSelectedIndex());
    }
    public void setErrorText(String value){
        ratingLabel.setText(value);
    }
    public void addAspectItem(Aspecto item){
        this.aspectListModel.addElement(item);
    }
    public void addCriticItem(ItemCritic item){
        this.criticaListModel.addElement(item);
    }
    public void deleteCriticItem(int row){
        this.criticaListModel.remove(row);
    }
    
    private  DefaultListModel<Aspecto> aspectListModel;
    private  DefaultListModel<ItemCritic> criticaListModel;
    private  JList<Aspecto> aspectList;
    private  JList<ItemCritic> criticsList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JScrollPane aspectScrollPane;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane criticsScrollPane;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel ratingLabel;
    // End of variables declaration//GEN-END:variables
}
