/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.starcritic.dam_proyect.view;

import com.starcritic.dam_proyect.model.pojo.itemList.ItemContent;
import com.starcritic.dam_proyect.model.pojo.itemList.ItemContentRender;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

/**
 *
 * @author jsb
 */
public class ListsUserDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListsUserDialog.class.getName());

    /**
     * Creates new form ListsUserDialog
     */
    public ListsUserDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initList();
        applyStyle();
        pack();
        setLocationRelativeTo(parent);
    }
    public ListsUserDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initList();
        applyStyle();
        pack();
        setLocationRelativeTo(parent);
    }

    private void applyStyle() {
        getContentPane().setBackground(UIStyle.BG_PRIMARY);
        backgroundPanel.setBackground(UIStyle.BG_PRIMARY);
        backgroundPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 24, 20, 24));

        searchLabel.setFont(new java.awt.Font(UIStyle.FONT_FAMILY, java.awt.Font.BOLD, 16));
        searchLabel.setForeground(UIStyle.ACCENT);
        UIStyle.styleField(searchTextField);
        UIStyle.stylePrimaryButton(searchButton);

        listUserScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(UIStyle.BORDER, 1, true));
        listUserScrollPane.getViewport().setBackground(UIStyle.BG_CARD);
        if (listsUserList != null) {
            UIStyle.styleList(listsUserList);
            listsUserList.setFont(new java.awt.Font(UIStyle.FONT_FAMILY, java.awt.Font.PLAIN, 15));
            listsUserList.setFixedCellHeight(36);
            listsUserList.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8));
        }

        UIStyle.stylePrimaryButton(addListButton);
        UIStyle.styleSecondaryButton(importButton);
        UIStyle.styleDangerButton(cancelButton);
        UIStyle.styleDangerButton(deleteButton);
        setTitle("Star Critic — Mis listas");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        backgroundPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        addListButton = new javax.swing.JButton();
        listUserScrollPane = new javax.swing.JScrollPane();
        importButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchLabel.setText("Buscar:");

        searchTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchTextField.setText("");

        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchButton.setText("Buscar");

        cancelButton.setText("Cancel");

        addListButton.setText("Añadir lista...");

        importButton.setText("Importar lista...");

        deleteButton.setText("Eliminar");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listUserScrollPane)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(searchLabel)
                        .addGap(18, 18, 18)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(importButton)
                        .addGap(18, 18, 18)
                        .addComponent(addListButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchButton))
                    .addComponent(searchLabel))
                .addGap(18, 18, 18)
                .addComponent(listUserScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(addListButton)
                    .addComponent(importButton)
                    .addComponent(deleteButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initList(){
        modelListUser = new DefaultListModel<>();
        listsUserList = new JList<>(modelListUser);
        listUserScrollPane.setViewportView(listsUserList);
    }
    public void setAddListButtonListener(ActionListener al){
        this.addListButton.addActionListener(al);
    }
    public void setCancelButtonListener(ActionListener al){
        this.cancelButton.addActionListener(al);
    }
    public void setSearchButtonListener(ActionListener al){
        this.searchButton.addActionListener(al);
    }
    public void setImportButtonListener(ActionListener al){
        this.importButton.addActionListener(al);
    }
    public String getSearchText(){
        return this.searchTextField.getText();
    }
    public void setImportButtonText(String value){
        this.importButton.setText(value);
    }
    public void setAddListButtonText(String value){
        this.addListButton.setText(value);
    }
    public void clearList(){
        modelListUser.clear();
    }
    public void addItemList(String value){
        modelListUser.addElement(value);
    }
    public void clearListUser() {
        modelListUser.clear();
        listsUserList.revalidate();
        listsUserList.repaint();
    }

    public void setListUserListener(MouseListener al){
        this.listsUserList.addMouseListener(al);
    }
    public void setListSelectionListener(javax.swing.event.ListSelectionListener l){
        this.listsUserList.addListSelectionListener(l);
    }
    public void setDeleteListListener(ActionListener al){
        this.deleteButton.addActionListener(al);
    }
    public int getSelectedList(){
        return this.listsUserList.getSelectedIndex();
    }
    public String getSelectedListValue(){
        return this.listsUserList.getSelectedValue();
    }
    public void enableListButtons(boolean value){
        enableAddListButton(value);
        enableImportButton(value);
    }
    public void enableAddListButton(boolean value) {
        this.addListButton.setEnabled(value);
        this.addListButton.setVisible(value);
    }

    public void enableImportButton(boolean value) {
        this.importButton.setEnabled(value);
        this.importButton.setVisible(value);
    }
    

    public void addPopupMenuItem(JMenuItem item){
        this.popupMenu.add(item);
    }

    public JPopupMenu getPopupMenu() {
        return popupMenu;
    }
    
    public void deleteItemList(int row){
        this.modelListUser.remove(row);
    }

    private DefaultListModel<String> modelListUser;
    private JList<String> listsUserList;    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addListButton;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton importButton;
    private javax.swing.JScrollPane listUserScrollPane;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
