/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.starcritic.dam_proyect.view;

import com.starcritic.dam_proyect.model.pojo.itemList.ItemContent;
import com.starcritic.dam_proyect.model.pojo.itemList.ItemContentRender;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;

/**
 *
 * @author jsb
 */
public class MainNavigationFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainNavigationFrame.class.getName());
    private static final int SCROLL_PANE_WIDTH = 876;
    private static final int SCROLL_PANE_HEIGHT = 91;
    private static final int LIST_CELL_WIDTH = 480;
    private static final int LIST_CELL_HEIGHT = 80;

    /**
     * Creates new form MainNavigationDialog
     */
    public MainNavigationFrame() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        initList();
        addListsRenderer();
        addLists();
        setTitle("Bandeja de entrada");
        applyStyle();
        pack();
        setLocationRelativeTo(null);
    }

    private void applyStyle() {
        getContentPane().setBackground(UIStyle.BG_PRIMARY);
        backgroundPanel.setBackground(UIStyle.BG_PRIMARY);
        backgroundPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(18, 22, 22, 22));

        cardPanel.setBackground(UIStyle.BG_PRIMARY);
        cardPanel.setOpaque(false);
        userPanel.setBackground(UIStyle.BG_PRIMARY);
        userPanel.setOpaque(false);

        userLabel.setFont(new java.awt.Font(UIStyle.FONT_FAMILY, java.awt.Font.BOLD, 14));
        userLabel.setForeground(UIStyle.TEXT);

        UIStyle.stylePrimaryButton(logInButton);
        logInButton.setFont(new java.awt.Font(UIStyle.FONT_FAMILY, java.awt.Font.BOLD, 18));
        UIStyle.styleIconButton(userButton);
        UIStyle.styleIconButton(searchButton);
        searchButton.setToolTipText("Buscar contenido");
        userButton.setToolTipText("Mi perfil");
        UIStyle.stylePrimaryButton(messageButton);
        UIStyle.stylePrimaryButton(statsButton);

        java.awt.Font sectionFont = new Font(UIStyle.FONT_FAMILY, java.awt.Font.BOLD, 15);
        for (JLabel l : new JLabel[]{filmLabel, serieLabel, videogamesLabel}) {
            l.setFont(sectionFont);
            l.setForeground(UIStyle.ACCENT);
            l.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, UIStyle.DIVIDER),
                    javax.swing.BorderFactory.createEmptyBorder(4, 2, 6, 0)));
        }
        filmLabel.setText("★  PELÍCULAS");
        serieLabel.setText("★  SERIES");
        videogamesLabel.setText("★  VIDEOJUEGOS");

        for (javax.swing.JScrollPane sp : new javax.swing.JScrollPane[]{filmScrollPane, seriesScrollPane, videogamesScrollPane}) {
            sp.setBorder(javax.swing.BorderFactory.createLineBorder(UIStyle.BORDER, 1, true));
            sp.getViewport().setBackground(UIStyle.BG_CARD);
            sp.setBackground(UIStyle.BG_CARD);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        backgroundPanel = new javax.swing.JPanel();
        cardPanel = new javax.swing.JPanel();
        logInButton = new javax.swing.JButton();
        userPanel = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        userButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        filmLabel = new javax.swing.JLabel();
        filmScrollPane = new javax.swing.JScrollPane();
        serieLabel = new javax.swing.JLabel();
        seriesScrollPane = new javax.swing.JScrollPane();
        videogamesLabel = new javax.swing.JLabel();
        videogamesScrollPane = new javax.swing.JScrollPane();
        messageButton = new javax.swing.JButton();
        statsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        cardPanel.setBackground(new java.awt.Color(255, 255, 255));
        cardPanel.setLayout(new java.awt.CardLayout());

        logInButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logInButton.setText("Iniciar Sesión");
        cardPanel.add(logInButton, "card2");

        userPanel.setBackground(new java.awt.Color(255, 255, 255));

        userLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        userLabel.setText("");

        userButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userButton)
                .addContainerGap())
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(userButton))
        );

        cardPanel.add(userPanel, "card3");

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magnifier_shootingstar_64.png"))); // NOI18N

        filmLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        filmLabel.setText("Peliculas:");

        filmScrollPane.setBorder(null);

        serieLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        serieLabel.setText("Series:");

        seriesScrollPane.setBorder(null);
        seriesScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        videogamesLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        videogamesLabel.setText("Videojuegos:");

        videogamesScrollPane.setBorder(null);
        videogamesScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        messageButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        messageButton.setText("Mensajes");

        statsButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        statsButton.setText("Estadísticas");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(statsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(messageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(filmScrollPane)
                    .addComponent(seriesScrollPane)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filmLabel)
                            .addComponent(serieLabel)
                            .addComponent(videogamesLabel)
                            .addComponent(videogamesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(statsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cardPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(messageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(filmLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filmScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(serieLabel)
                .addGap(18, 18, 18)
                .addComponent(seriesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(videogamesLabel)
                .addGap(18, 18, 18)
                .addComponent(videogamesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void initList(){
        modelFilms = new DefaultListModel<>();
        modelSeries = new DefaultListModel<>();
        modelVideogames = new DefaultListModel<>();
        filmList = new JList<>(modelFilms);
        seriesList = new JList<>(modelSeries);
        videogamesList = new JList<>(modelVideogames); 
    }
    private void addListsRenderer(){
        filmList.setCellRenderer(new ItemContentRender());
        filmList.setLayoutOrientation(JList.HORIZONTAL_WRAP);
        filmList.setVisibleRowCount(1);
        filmList.setFixedCellWidth(LIST_CELL_WIDTH);
        filmList.setFixedCellHeight(LIST_CELL_HEIGHT);
        seriesList.setCellRenderer(new ItemContentRender());
        seriesList.setLayoutOrientation(JList.HORIZONTAL_WRAP);
        seriesList.setVisibleRowCount(1);
        seriesList.setFixedCellWidth(LIST_CELL_WIDTH);
        seriesList.setFixedCellHeight(LIST_CELL_HEIGHT);
        videogamesList.setCellRenderer(new ItemContentRender());
        videogamesList.setLayoutOrientation(JList.HORIZONTAL_WRAP);
        videogamesList.setVisibleRowCount(1);
        videogamesList.setFixedCellWidth(LIST_CELL_WIDTH);
        videogamesList.setFixedCellHeight(LIST_CELL_HEIGHT);
    }
    private void addLists(){
        filmScrollPane.setViewportView(filmList);
        seriesScrollPane.setViewportView(seriesList);
        videogamesScrollPane.setViewportView(videogamesList);
        lockScrollPaneWidth(filmScrollPane, SCROLL_PANE_HEIGHT);
        lockScrollPaneWidth(seriesScrollPane, SCROLL_PANE_HEIGHT);
        lockScrollPaneWidth(videogamesScrollPane, SCROLL_PANE_HEIGHT);
    }

    private void lockScrollPaneWidth(JScrollPane scrollPane, int height){
        Dimension fixed = new Dimension(SCROLL_PANE_WIDTH, height);
        scrollPane.setPreferredSize(fixed);
        scrollPane.setMaximumSize(fixed);
        scrollPane.setMinimumSize(fixed);
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    }
    
    public void addItemPopupMenu(JMenuItem item){
        popupMenu.add(item);
    }
    public void addElementFilm(ItemContent element){
        modelFilms.addElement(element);
    }
    public void addElementSerie(ItemContent element){
        modelSeries.addElement(element);
    }
    public void addElementVideogame(ItemContent element){
        modelVideogames.addElement(element);
    }   
    
    public void setUserButtonListener (ActionListener al){
        userButton.addActionListener(al);
    }

    public JPopupMenu getPopupMenu() {
        return popupMenu;
    }
    
    public JButton getUserButton() {
        return userButton;
    }

    public void setUserButton(JButton userButton) {
        this.userButton = userButton;
    }
    
    public void setSearchButtonListener (ActionListener al){
        searchButton.addActionListener(al);
    }
    public void setLogInButtonListener(ActionListener al){
        logInButton.addActionListener(al);
    }
    public JList<ItemContent> getFilmList() {
        return filmList;
    }

    public void setMessageButtonListener (ActionListener al){
         messageButton.addActionListener(al);
    }  
    
        public void setStatsButtonListener (ActionListener al){
        statsButton.addActionListener(al);
    }
    
    public JList<ItemContent> getSeriesList() {
        return seriesList;
    }

    public JList<ItemContent> getVideogamesList() {
        return videogamesList;
    }
    
    private void setVerticalSize(){
        this.setSize(this.getSize().width, 550);
    }
    public void enableUserOptions(boolean status){
        userPanel.setEnabled(status);
        userPanel.setVisible(status);
        messageButton.setEnabled(status);
        messageButton.setVisible(status);

    }
    public void enableLogIn(boolean status){
        logInButton.setEnabled(status);
        logInButton.setVisible(status);
    }
    public void setLabelUser (String value){
        userLabel.setText(value);
    }
    
    public void clearPopupMenu(){
        popupMenu.removeAll();
    }

    public void clearFilms()      { modelFilms.clear(); }
    public void clearSeries()     { modelSeries.clear(); }
    public void clearVideogames() { modelVideogames.clear(); }

    public void setFilmListListener(MouseListener ml)      { filmList.addMouseListener(ml); }
    public void setSeriesListListener(MouseListener ml)    { seriesList.addMouseListener(ml); }
    public void setVideogamesListListener(MouseListener ml){ videogamesList.addMouseListener(ml); }
    private DefaultListModel<ItemContent> modelFilms;
    private DefaultListModel<ItemContent> modelSeries;
    private DefaultListModel<ItemContent> modelVideogames;
    private JList<ItemContent> filmList;
    private JList<ItemContent> seriesList;
    private JList<ItemContent> videogamesList;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel filmLabel;
    private javax.swing.JScrollPane filmScrollPane;
    private javax.swing.JButton logInButton;
    private javax.swing.JButton messageButton;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel serieLabel;
    private javax.swing.JScrollPane seriesScrollPane;
    private javax.swing.JButton statsButton;
    private javax.swing.JButton userButton;
    private javax.swing.JLabel userLabel;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel videogamesLabel;
    private javax.swing.JScrollPane videogamesScrollPane;
    // End of variables declaration//GEN-END:variables
}
