/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.starcritic.dam_proyect.view;

import com.starcritic.dam_proyect.model.pojo.itemList.ItemMessage;
import com.starcritic.dam_proyect.model.pojo.itemList.ItemMessageRender;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author jsanbaq
 */
public class MessagesDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MessagesDialog.class.getName());

    /**
     * Creates new form MessagesDialog
     */
    public MessagesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        applyStyle();
        initList();
        pack();
        setLocationRelativeTo(parent);
    }
    
    public MessagesDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        applyStyle();
        initList();
        pack();
        setLocationRelativeTo(parent);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        messagesScrollPane = new javax.swing.JScrollPane();
        titleLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        messagesScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setText("Mensajes del Sistema");

        cancelButton.setText("Cancelar");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messagesScrollPane)
                .addContainerGap())
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(481, 481, 481)
                .addComponent(cancelButton)
                .addGap(0, 35, Short.MAX_VALUE))
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(messagesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applyStyle(){
        getContentPane().setBackground(UIStyle.BG_PRIMARY);
        backgroundPanel.setBackground(UIStyle.BG_PRIMARY);
        backgroundPanel.setBorder(BorderFactory.createEmptyBorder(20, 24, 20, 24));

        messagesScrollPane.setBorder(BorderFactory.createLineBorder(UIStyle.BORDER, 1, true));
        messagesScrollPane.getViewport().setBackground(UIStyle.BG_CARD);
        
        UIStyle.styleDangerButton(cancelButton);
        
        setTitle("Star Critic — Mensajes");
        
        titleLabel.setFont(new Font(UIStyle.FONT_FAMILY, Font.BOLD, 26));
        titleLabel.setForeground(UIStyle.TITLE);
    }
    
    private void initList(){
        messageListModel = new DefaultListModel<>();
        messageList = new JList<>(messageListModel);
        messageList.setCellRenderer(new ItemMessageRender());
        UIStyle.styleList(messageList);
        messagesScrollPane.setViewportView(messageList);
    }

    public void setCancelButtonListener(ActionListener al){
        cancelButton.addActionListener(al);
    }

    public void setMessageListListener(MouseListener ma){
        messageList.addMouseListener(ma);
    }

    public int getSelectedMessage(){
        return messageList.getSelectedIndex();
    }

    public ItemMessage getMessageAt(int row){
        return messageListModel.get(row);
    }

    public void clearMessages(){
        messageListModel.clear();
    }

    public void addItemList(ItemMessage item){
        this.messageListModel.addElement(item);
    }
    private  DefaultListModel<ItemMessage> messageListModel;
    private  JList<ItemMessage> messageList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane messagesScrollPane;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
