/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.starcritic.dam_proyect.view;

import java.awt.event.ActionListener;

/**
 * Diálogo de perfil del usuario: muestra y permite editar avatar, nombre y
 * correo electrónico, así como solicitar la certificación de crítico.
 *
 * @author Jesús Santos Baquero
 */
public class ProfileDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProfileDialog.class.getName());

    /**
     * Creates new form ProfileDialog
     */
    public ProfileDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        applyStyle();
        pack();
        setLocationRelativeTo(parent);
    }

    private void applyStyle() {
        getContentPane().setBackground(UIStyle.BG_PRIMARY);
        backgroundPanel.setBackground(UIStyle.BG_PRIMARY);
        backgroundPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 30, 24, 30));

        UIStyle.styleFormLabel(userLabel);
        UIStyle.styleFormLabel(nameLabel);
        UIStyle.styleFormLabel(addressLabel);
        UIStyle.styleField(userTextField);
        UIStyle.styleField(nameTextField);
        UIStyle.styleField(addressTextField);

        resultLabel.setFont(new java.awt.Font(UIStyle.FONT_FAMILY, java.awt.Font.ITALIC, 12));
        resultLabel.setForeground(UIStyle.SUCCESS);

        UIStyle.stylePrimaryButton(changeUserButton);
        UIStyle.styleSecondaryButton(statsButton);
        UIStyle.styleSecondaryButton(jButton1);
        UIStyle.styleDangerButton(cancelButton);
        setTitle("Star Critic — Mi perfil");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        changeUserButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        statsButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        userLabel.setText("Usuario: ");

        userTextField.setText("");

        changeUserButton.setText("Configurar");

        nameLabel.setText("Nombre:");

        addressLabel.setText("Dirección:");

        nameTextField.setText("");

        addressTextField.setText("");

        cancelButton.setText("Cancelar");

        jButton1.setText("Cambiar contraseña");

        statsButton.setText("Mis estadísticas...");

        resultLabel.setText("");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(statsButton)
                        .addGap(18, 18, 18)
                        .addComponent(changeUserButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(resultLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(addressLabel)
                                .addGap(18, 18, 18)
                                .addComponent(addressTextField))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(nameTextField))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(userLabel)
                                .addGap(18, 18, 18)
                                .addComponent(userTextField)))))
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel)
                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeUserButton)
                    .addComponent(cancelButton)
                    .addComponent(jButton1)
                    .addComponent(statsButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setCancelButtonListener(ActionListener al){
        this.cancelButton.addActionListener(al);
    }
    public void setChangeUserButtonListener(ActionListener al){
        this.changeUserButton.addActionListener(al);
    }
    public void setChangePasswordButtonListener(ActionListener al){
        this.jButton1.addActionListener(al);
    }
    public void setStatsButtonListener(ActionListener al){
        this.statsButton.addActionListener(al);
    }
    
    public String getButtonConfigurarText(){
        return this.changeUserButton.getText();
    }
    public String getUser(){
        return this.userTextField.getText();
    }
    public void setUser(String value){
        this.userTextField.setText(value);
    }
    public String getName(){
        return this.nameTextField.getText();
    }
    public void setName(String value){
        this.nameTextField.setText(value);
    }
    public String getAddress(){
        return this.addressTextField.getText();
    }
    public void setAddress(String value){
        this.addressTextField.setText(value);
    }
    public void setResultLabel(String value){
        this.resultLabel.setText(value);
    }
    public void setFieldsEditable(boolean enabled){
        this.userTextField.setEnabled(enabled);
        this.nameTextField.setEnabled(enabled);
        this.addressTextField.setEnabled(enabled);
    }
    public void setChangeUserButtonText(String text){
        this.changeUserButton.setText(text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton changeUserButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton statsButton;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
}
