/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.starcritic.dam_proyect.view;

import com.starcritic.dam_proyect.model.pojo.bd.Origen;
import com.starcritic.dam_proyect.model.pojo.itemList.ItemContent;
import com.starcritic.dam_proyect.model.pojo.itemList.ItemContentRender;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 * Diálogo de búsqueda de contenidos con filtros por tipo y origen
 * (OMDb, RAWG o catálogo local) y resultados paginados.
 *
 * @author Jesús Santos Baquero
 */
public class SearchDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchDialog.class.getName());

    /**
     * Creates new form SearchDialog
     */
    public SearchDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initList();
        applyStyle();
        pack();
        setLocationRelativeTo(parent);
    }
    public SearchDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initList();
        applyStyle();
        pack();
        setLocationRelativeTo(parent);
    }

    private void applyStyle() {
        getContentPane().setBackground(UIStyle.BG_PRIMARY);
        backgroundPanel.setBackground(UIStyle.BG_PRIMARY);
        backgroundPanel.setBorder(BorderFactory.createEmptyBorder(20, 24, 20, 24));

        searchLabel.setFont(new Font(UIStyle.FONT_FAMILY, Font.BOLD, 18));
        searchLabel.setForeground(UIStyle.ACCENT);
        UIStyle.styleField(searchTextField);
        searchTextField.setFont(new Font(UIStyle.FONT_FAMILY, Font.PLAIN, 15));
        UIStyle.stylePrimaryButton(searchButton);
        searchButton.setFont(new Font(UIStyle.FONT_FAMILY, Font.BOLD, 14));

        UIStyle.styleRadio(filmsRadioButton);
        UIStyle.styleRadio(seriesRadioButton);
        UIStyle.styleRadio(videojuegoRadioButton);

        filmScrollPane.setBorder(BorderFactory.createLineBorder(UIStyle.BORDER, 1, true));
        filmScrollPane.getViewport().setBackground(UIStyle.BG_CARD);
        if (searchList != null) {
            UIStyle.styleList(searchList);
        }

        UIStyle.styleSecondaryButton(beforeButton);
        UIStyle.styleSecondaryButton(afterButton);
        UIStyle.styleDangerButton(cancelButton);
        UIStyle.styleDangerButton(deleteButton);
        actualLabel.setFont(new Font(UIStyle.FONT_FAMILY, Font.BOLD, 13));
        actualLabel.setForeground(UIStyle.TEXT_MUTED);
        setTitle("Star Critic — Buscar");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemButtonGroup = new javax.swing.ButtonGroup();
        backgroundPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        filmsRadioButton = new javax.swing.JRadioButton();
        seriesRadioButton = new javax.swing.JRadioButton();
        videojuegoRadioButton = new javax.swing.JRadioButton();
        filmScrollPane = new javax.swing.JScrollPane();
        searchButton = new javax.swing.JButton();
        beforeButton = new javax.swing.JButton();
        actualLabel = new javax.swing.JLabel();
        afterButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchLabel.setText("Buscar:");

        searchTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchTextField.setText("");

        itemButtonGroup.add(filmsRadioButton);
        filmsRadioButton.setText("Peliculas");

        itemButtonGroup.add(seriesRadioButton);
        seriesRadioButton.setText("Series");

        itemButtonGroup.add(videojuegoRadioButton);
        videojuegoRadioButton.setText("Videojuegos");

        filmScrollPane.setBorder(null);
        filmScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchButton.setText("Buscar");

        beforeButton.setText("Anterior");

        actualLabel.setText("");

        afterButton.setText("Siguiente");

        cancelButton.setText("Cancelar");

        deleteButton.setText("Eliminar...");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filmScrollPane)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(filmsRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(seriesRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(videojuegoRadioButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(searchLabel)
                                .addGap(18, 18, 18)
                                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(deleteButton)
                                .addGap(118, 118, 118)
                                .addComponent(beforeButton)
                                .addGap(18, 18, 18)
                                .addComponent(actualLabel)
                                .addGap(18, 18, 18)
                                .addComponent(afterButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelButton)))))
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchTextField)
                    .addComponent(searchLabel)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filmsRadioButton)
                    .addComponent(seriesRadioButton)
                    .addComponent(videojuegoRadioButton))
                .addGap(18, 18, 18)
                .addComponent(filmScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beforeButton)
                    .addComponent(actualLabel)
                    .addComponent(afterButton)
                    .addComponent(cancelButton)
                    .addComponent(deleteButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setSearchButtonListener(ActionListener al){
        this.searchButton.addActionListener(al);
    }

    public String getSearchText(){
        return this.searchTextField.getText();
    }
    private void initList(){
        modelSearch = new DefaultListModel<>();
        searchList = new JList<>(modelSearch);
        searchList.setCellRenderer(new ItemContentRender());
        filmScrollPane.setViewportView(searchList);
    }
    public void clearList(){
        modelSearch.clear();
    }
    public void addElementSearch(ItemContent item){
        modelSearch.addElement(item);
    }
    public String getItemListId(int num){
        return modelSearch.get(num).getId();
    }
    
    public Origen getItemListOrigen(int num){
        return modelSearch.get(num).getOrigen();
    }
    
    public void setSearchListListener(MouseListener ml){
        searchList.addMouseListener(ml);
    }
    
    public void setAfterButtonListener(ActionListener al){
        afterButton.addActionListener(al);
    }
    public void setBeforeButtonListener(ActionListener al){
        beforeButton.addActionListener(al);
    }
    public void setRadioButtonGroupListener(ActionListener al){
        this.filmsRadioButton.addActionListener(al);
        this.seriesRadioButton.addActionListener(al);
        this.videojuegoRadioButton.addActionListener(al);
    }

    public void setCancelButtonListener(ActionListener al){
        this.cancelButton.addActionListener(al);
    }
    public void setDeleteButtonListener(ActionListener al){
        this.deleteButton.addActionListener(al);
    }
    public int getSelectedRow(){
        return searchList.getSelectedIndex();
    }
    
    public boolean isFilmSelected(){
        return filmsRadioButton.isSelected();
    }
    public boolean isSeriesSelected(){
        return seriesRadioButton.isSelected();
    }
    public boolean isVideogamesSelected(){
        return videojuegoRadioButton.isSelected();
    }
    public void setFilmSelect(boolean value){
        this.filmsRadioButton.setSelected(value);
    }
    
    public void setTextLabel(String value){
        this.actualLabel.setText(value);
    }
    public void enablePassButton(boolean value){
        this.afterButton.setEnabled(value);
        this.afterButton.setVisible(value);
        this.beforeButton.setEnabled(value);
        this.beforeButton.setVisible(value);
    }
    public void enableRadioButtons(boolean value){
        this.filmsRadioButton.setEnabled(value);
        this.filmsRadioButton.setVisible(value);
        this.seriesRadioButton.setEnabled(value);
        this.seriesRadioButton.setVisible(value);
        this.videojuegoRadioButton.setEnabled(value);
        this.videojuegoRadioButton.setVisible(value);
    }
    public void enableDeleteButton(boolean value){
        this.deleteButton.setEnabled(value);
        this.deleteButton.setVisible(value);
    }
    
    public void setTextPassOptions(String value1, String value2, String value3){
        this.actualLabel.setText(value2);
        this.beforeButton.setText(value1);
        this.afterButton.setText(value3);
    }
    public void deleteListElement(int row){
        this.modelSearch.remove(row);
    }
    
    private DefaultListModel<ItemContent> modelSearch;
    private JList<ItemContent> searchList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualLabel;
    private javax.swing.JButton afterButton;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton beforeButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JScrollPane filmScrollPane;
    private javax.swing.JRadioButton filmsRadioButton;
    private javax.swing.ButtonGroup itemButtonGroup;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JRadioButton seriesRadioButton;
    private javax.swing.JRadioButton videojuegoRadioButton;
    // End of variables declaration//GEN-END:variables
}
